// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjk8056NIZYXemOQCv6Yw_KTCbPm4dAag',
    appId: '1:296340988883:web:be3db85e6f8d44b16b4526',
    messagingSenderId: '296340988883',
    projectId: 'coffe-app-d0cc0',
    authDomain: 'coffe-app-d0cc0.firebaseapp.com',
    storageBucket: 'coffe-app-d0cc0.firebasestorage.app',
    measurementId: 'G-MHWCB0H3CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3RLgG8bb7zDh_oxCRacUBuolvJDyDVk',
    appId: '1:296340988883:android:b1baf809edbb34ac6b4526',
    messagingSenderId: '296340988883',
    projectId: 'coffe-app-d0cc0',
    storageBucket: 'coffe-app-d0cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2F59P9lw8N0tUylvRFBbt142UHG1RenI',
    appId: '1:296340988883:ios:2d1858fb14a6a76d6b4526',
    messagingSenderId: '296340988883',
    projectId: 'coffe-app-d0cc0',
    storageBucket: 'coffe-app-d0cc0.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2F59P9lw8N0tUylvRFBbt142UHG1RenI',
    appId: '1:296340988883:ios:2d1858fb14a6a76d6b4526',
    messagingSenderId: '296340988883',
    projectId: 'coffe-app-d0cc0',
    storageBucket: 'coffe-app-d0cc0.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjk8056NIZYXemOQCv6Yw_KTCbPm4dAag',
    appId: '1:296340988883:web:06792cfc02a799306b4526',
    messagingSenderId: '296340988883',
    projectId: 'coffe-app-d0cc0',
    authDomain: 'coffe-app-d0cc0.firebaseapp.com',
    storageBucket: 'coffe-app-d0cc0.firebasestorage.app',
    measurementId: 'G-FFK7STE6DZ',
  );
}
