import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure


// Screens
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';
import 'screens/admin_screen.dart';
import 'screens/home_screen.dart';
import 'screens/admin_menu_screen.dart';

// Firebase Auth
import 'package:firebase_auth/firebase_auth.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const CoffeeShopApp());
}

class CoffeeShopApp extends StatelessWidget {
  const CoffeeShopApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '☕ Coffee Shop',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.brown,
        scaffoldBackgroundColor: const Color(0xFFF8F5F2),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF6F4E37),
          elevation: 4,
          titleTextStyle: TextStyle(
            fontFamily: 'Poppins',
            fontWeight: FontWeight.bold,
            fontSize: 22,
            color: Colors.white,
          ),
        ),
        textTheme: const TextTheme(
          bodyMedium: TextStyle(fontFamily: 'Poppins', color: Colors.black87),
        ),
      ),
      home: const AuthWrapper(), // ✅ Smart routing based on login & role
     routes: {
  '/login': (context) => const LoginScreen(),
  '/register': (context) => const RegisterScreen(),
  '/home': (context) => const HomeScreen(),
  '/admin': (context) => const AdminScreen(),
  '/admin/menu': (context) => const AdminMenuScreen(),
},

    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  Future<String?> _getUserRole() async {
    // This is a placeholder — soon we’ll fetch the role from Firestore
    // You can store the user role (admin/client) in Firestore under "users" collection
    // Example:
    //   users/{uid}/role: 'admin' or 'client'
    //
    // For now, return a hardcoded 'admin' or 'client' for testing.
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return null;
    return 'client'; // change to 'admin' for testing
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 🔸 User not logged in
        if (!snapshot.hasData) return const LoginScreen();

        // 🔸 User logged in → check role
        return FutureBuilder<String?>(
          future: _getUserRole(),
          builder: (context, roleSnapshot) {
            if (roleSnapshot.connectionState == ConnectionState.waiting) {
              return const Scaffold(
                body: Center(child: CircularProgressIndicator(color: Colors.brown)),
              );
            }

            final role = roleSnapshot.data;
            if (role == 'admin') {
              return const AdminScreen();
            } else {
              return const HomeScreen();
            }
          },
        );
      },
    );
  }
}
